### ISSUE TITLE
Get transactions from a wallet

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#133]
Add a thin wrapper on `fuel-core`'s `transactions()` method bound to `Provider` and `Wallet` so that SDK users can use `fuels-rs` to get transactions from a given wallet (bound to `Wallet`) and any transactions given a some parameters (bound to `Provider`).

**Comment by Salka1988** [comment]
Function transactions() returns io::Result<PaginatedResult<TransactionResponse, String>>.

The question is whether to leave the option parameter request: PaginationRequest> <String> in the new functions so that the user can specify the number of transactions he wants to return, or I will omit this parameter and return all transactions related to Wallet or Provider?
