### ISSUE TITLE
Allow the SDK to start a node using just the `fuel-core` binary

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/fuels-rs#237]
For the EthCC workshop, will we need to distribute requirements as binaries to reduce ramp-up time. Then during the workshop, people will write Sway code + test it using the SDK. Meaning, the SDK will need to be able to start a node using just the `fuel-core` binary.

EthCC is in mid-July, though hopefully we would be able to have this component implemented by mid-June, so that we can explore alternative options, if this option becomes intractable.

Relevant slack discussion:

```
Emily Herbert  8 minutes ago
Can the SDK start a node using just the fuel-core binary?

[Rodrigo Araújo](https://app.slack.com/team/U022YCJ2W2Z)  8 minutes ago
Oh, not currently no

[Rodrigo Araújo](https://app.slack.com/team/U022YCJ2W2Z)  7 minutes ago
Not too hard to implement that tho

John Adler:pudding:  7 minutes ago
Oh! Then how does the SDK start a node?

John Adler:pudding:  7 minutes ago
Does it start an instance of the VM in-process?

[Rodrigo Araújo](https://app.slack.com/team/U022YCJ2W2Z)  7 minutes ago
Using FuelClient:
let srv = FuelService::new_node(config).await.unwrap();
let client = FuelClient::from(srv.bound_address);
(edited)
:eyes:
2


[Rodrigo Araújo](https://app.slack.com/team/U022YCJ2W2Z)  6 minutes ago
Does it start an instance of the VM in-process?
That’s gonna happen in the FuelClient

Emily Herbert  6 minutes ago
Ahh

Emily Herbert  5 minutes ago
Would we be able to hack together on allowing the SDK to start a node using just the fuel-core binary? That would be a better workshop experience I think, if we are able to accomplish that
```

**Comment by emilyaherbert** [comment]
Assigning this one to you @digorithm based on our discussion. Please ping me if you want to hack on this together or chat about ideas!

**Comment by Salka1988** [comment]
If I understood you correctly, you want your attendees to have a pleasant experience during the workshop, where pleasant == quick compile times.
In order to speed up the compile times, you would like the SDK to not have to build the fuel-core.
The SDK has a non-dev transient dependency on fuel-core.
I've thought about two ways of going about removing the fuel-core dependency from the SDK:
#1 way:
------
We will require every user of the SDK to provide a fuel-core binary at a predefined location before using the SDK.
The upside of this is that we can then rewrite parts of the SDK that use fuel-core to just delegate to the binary.
The downside is that we're going to ruin the user experience and most probably our CI due to the need for a binary at a predefined location.
I don't see this as a realistic solution due to the above, but if you're ok with this being on a feature branch ready for you to use it one-time during the workshop then this solution is quick and can be thrown away easily. I just don't like the idea of merging it into master.
#2 (cleaner) way:
----------------
We add some compile time configuration so that SDK users can choose between providing a compiled fuel-core binary or having a dependency on fuel-core.
I have a gut feeling this can be implemented through cfg but I haven't had experience with it before and could take some doing before I get it right.
The upside is that we can merge this and you can use it in future workshops and our CI wouldn't be broken nor our user experience because we would be defaulting to being dependent on fuel-core.
The downside is that it might take more time for me to implement it, if it's possible at all.
----
In either case you'd have to provide the binary at the time of the workshop and it should be placed in a predefined/configurable path for the SDK to use it.

**Comment by emilyaherbert** [comment]
Yep! We chatted about this offline, but just to keep the GitHub record current for anyone else that may hop on this issue...

> pleasant == quick compile times

The word "compile" is used in multiple places. There is "compiling the Sway compiler" (which I am trying to avoid) and "compiling Sway code using the compiled Sway compiler" (which we do not want to avoid). It should be possible to distribute the compiler Sway compiler as a binary, and use that inside of the SDK, in order to compile Sway code, which is what this issue is tracking.

> I don't see this as a realistic solution due to the above, but if you're ok with this being on a feature branch ready for you to use it one-time during the workshop then this solution is quick and can be thrown away easily. I just don't like the idea of merging it into master.

Agreed, let's try to avoid this if we can. But, we know that it is possible to do if we need it in a pinch.

> We add some compile time configuration so that SDK users can choose between providing a compiled fuel-core binary or having a dependency on fuel-core.

SGTM 👍

**Comment by adlerjohn** [comment]
Can't you just have `fuel-core` in your PATH, instead of a predefined location?

**Comment by Salka1988** [comment]
I was able to run node-service in the `SDK` via the fuel-core bin. file, but my problem is the Config files that are in the fuel-core. Config files configure nodes (address, how many coins ... etc)
We need them to make the same functionality.
```rust
    let config = Config {
        chain_conf: ChainConfig {
            initial_state: Some(StateConfig {
                coins: Some(coin_configs),
                ..StateConfig::default()
            }),
            ..ChainConfig::local_testnet()
        },
        database_type: DbType::InMemory,
        utxo_validation: true,
        ..node_config
    };

    let srv = FuelService::new_node(config).await.unwrap();
```


My suggestions are as follows:

- Let's create a JSON for each Config file we need. (Config files are eventually converted to JSON files).

- We could extract the Config files into a special 'crate' to separate them from the fuel-core and thus use them wherever we need them.

- We could duplicate the code :)
