### ISSUE TITLE
Sway function named 'new' leads to collision

### ISSUE THREAD

**Issue by MujkicA** [FuelLabs/fuels-rs#277]
The abigen macro generates a `new` method for creating contract instances. If the ABI includes a function named `new` this will result in a naming collision.

**Comment by hal3e** [comment]
I had a look at this error. Rust doesn't support overloaded functions/methods, so whatever we choose for the name a collision can still happen.

``` rust    
impl MyContract {
        pub fn new(contract_id: String, wallet: LocalWallet) -> Self {
            let contract_id = ContractId::from_str(&contract_id).unwrap();
            Self {
                contract_id,
                wallet,
            }
        }
        ///Calls the contract's `new` (0x00000000b833a3fa) function
        pub fn new(&self, input: (u64, bool)) -> ContractCall<()> {
```
@digorithm could we move this function outside of the `impl MyContract` and give it some generic name like `new_contract`?

Another option would be that `sway` doesn't allow this function name.

**Comment by digorithm** [comment]
> @digorithm could we move this function outside of the impl MyContract and give it some generic name like new_contract?

I _think_ you need that to be generated here, it's how the `new` in `let instance = MyContract::new(id.to_string(), wallet);` is generated... Unless you have a different idea? 

This treatment definitely needs to be on the SDK though, Sway itself not allowing that name would be a bit weird.

**Comment by segfault-magnet** [comment]
@digorithm this seems to be deadlocked.

It seems to me that whatever name we choose there is nothing stopping Sway developers from creating a function with the same name (since naming rules are very similar/identical between rust and sway). 

Another way might be to do what @hal3e suggested and create a new struct that will `impl` the API of the contract:
```rust
instance.caller.new();
```
Where caller will be a struct which will delegate back to `MyContract` through a reference if needed. It will be constructed by `MyContract` through the `SomeStruct{}` syntax and given a reference to itself, like a [method object](https://refactoring.guru/replace-method-with-method-object).

Or something like that. Somehow that feels not worth the hassle. 

I suggest we keep our own `new` as a way to initialize the contract but change the method binding name to something like _new (like safe_ident does) to avoid all identifiers already present in `MyContract`. 

We will then proceed to document this behavior so as not to come as a surprise.

@digorithm Thoughts?
