### ISSUE TITLE
Change call unwrap to not panic if transaction reverts or panics

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuels-rs#295]
Currently, if a transaction reverts or panics, `script.call(&client).await` returns an error variant rather than an ok variant. This makes it impossible to view the receipts and actually debug what's wrong. This should be changed to always return the ok variant if the transaction is executed successfully, regardless of whether execution reverted/panicked or not.

**Comment by adlerjohn** [comment]
Rather than `Option`, how about making `CallResponse.value` a `Result`?

**Comment by vnepveu** [comment]
> Rather than `Option`, how about making `CallResponse.value` a `Result`?
I like that idea but there is still the issue of needing to `unwrap` everytime. Maybe I'm making it a bigger deal than it is though.

**Comment by adlerjohn** [comment]
If you want to avoid unwrapping multiple times on a single result then just save the inner value. If you're referring to having to unwrap for each call...then you currently have to do it anyways!

**Comment by vnepveu** [comment]
To be clear, if `ResponseCall.value` becomes a `Result<D, Error>` instead of `D` type (where `D` is the Sway return type), then the workflow would go from:

```rust
let response = MyContract.my_method(arg1, arg2).call().await.unwrap(); // Unwrap the `Result<CallResponse, Error>
assert_eq!(response.value, expected); // I don't need to unwrap the value field, super clean!
```
to 
```rust
let response = MyContract.my_method(arg1, arg2).call().await.unwrap();  // Unwrap the `Result<CallResponse, Error>
assert_eq!(response.value.unwrap(), expected); // Here I called unwrap 2 times
```.
I find it more cumbersome, but also struggle to see another solution. Do you think this way is fine?

**Comment by digorithm** [comment]
In my opinion, I don't think it's good adding another `.unwrap()` to the usual workflow. Some people already mentioned the length of the `.my_method(arg1, arg2).call().await.unwrap();` chain. What we would be effectively doing here would be turning it into `.my_method(arg1, arg2).call().await.unwrap().unwrap();` (i.e. most people just want the value right away).

**Comment by digorithm** [comment]
Isn't the main problem described here the lack of debuggability when `.my_method(arg1, arg2).call().await.unwrap();` fails, making the returned `Result<CallResponse<D>, Error>` be the `Error` and therefore losing the receipts in `CallResponse<D>`?

We could keep the current behavior (`Error` return when the executed call reverts/panics internally) but extend `Error` with a new `ContractCallError(Vec<Receipt>)` that includes a list of all the receipts. Currently we do something like this, but pass in just the reason, not the receipts:

```Rust
let status = fuel_client.transaction_status(&tx_id).await?;
      match status {
          TransactionStatus::Failure { reason, .. } => Err(Error::ContractCallError(reason)),
          _ => Ok(receipts),
      }
```

So that `ContractCallError(String)` would become `ContractCallError(Vec<Receipt>)`. 

Advantage: we would keep the same workflow (`.my_method(arg1, arg2).call().await.unwrap();`) while solving the problem discussed in here (`impossible to view the receipts and actually debug what's wrong.`).

**Comment by vnepveu** [comment]
Oh yes that's much much better! Good idea, I'm glad I opened this discussion haha.
