### ISSUE TITLE
refactor: change the launch functions and wallet setup

### ISSUE THREAD

**Issue by vnepveu** [FuelLabs/fuels-rs#312]
After discussion:
There should be two `launch` function: 
- `launch_provider_and_get_wallet` -> you only get one wallet, with a default provider
- `launch_custom_provider_and_get_wallets` -> you launch a custom provider, and get as many wallets as you want.

The `setup_test_client` function should probably me made private.

- I think `WalletConfig` would benefit from having a `::single()` function that give out one wallet.

**Comment by MujkicA** [comment]
There is 3 functions that setup a provider and wallets: 

`launch_provider_and_get_single_wallet`
`launch_provider_and_get_wallets`
`launch_custom_provider_and_get_single_wallet`

Since we opted for making the names extra verbose, I think its fine. 
However, IMO `launch_custom_provider_and_get_single_wallet` should also accept `WalletConfig` and be able to setup multiple wallets. Since its a niche use-case I think its ok if we don't provide a shorthand for just getting a single wallet.

**Comment by vnepveu** [comment]
There is also `setup_test_provider`, `setup_test_client`.

**Comment by vnepveu** [comment]
I think that's too much. We should have something like:
`launch_provider_and_get_wallet` (default case, people want out of the box provider with a single wallet)
and `launch_custom_provider_and_get_wallets`  (can customize wallets and launcher).

`setup_*` functions I'm not sure what to do with them.

**Comment by MujkicA** [comment]
The change to the `launch_*` methods sounds good. 
As for `setup_test_client`, I think we can make it private. `setup_test_provider` just introduces a wrapper while not taking away any of functionality.

**Comment by vnepveu** [comment]
Agree with this I think, updated the issue description.
