### ISSUE TITLE
Create a `B512` type to match `std::b512::B512`

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/fuels-rs#688]
This is implemented in Sway as:
```
pub struct B512 {
    bytes: [b256; 2],
}
```

I'm currently working around this by making contract functions accept 2 `b256` values and constructing the `B512` in sway.

**Comment by arboleya** [comment]
@luizstacio @digorithm Should I consider this type for the new [ABI `typegen`](https://github.com/FuelLabs/fuels-ts/pull/570)?

Initially, I followed only the primitives listed here:
 - https://fuellabs.github.io/sway/v0.30.1/basics/built_in_types.html#primitive-types

The only mention of `B512` is under _**signature recovery**_:
 - https://fuellabs.github.io/sway/v0.30.1/blockchain-development/hashing_and_cryptography.html?highlight=B512#signature-recovery

**Comment by nfurfaro** [comment]
`B512` is a stdlib type, like `Address`, `EvmAddress`, `Option` & `Result`.
It seems that sooner or later, for every type added to `std` there will be a request to use that type in the SDK.
Perhaps moving forward, as new types are proposed for `std` we can coordinate with the SDK teams to roll out support more in parallel?

**Comment by arboleya** [comment]
Interesting. I wasn't paying attention to this.

Are these `stdlib` types documented somewhere?

I found only [this](https://fuellabs.github.io/sway/v0.30.1/introduction/standard_library.html) that points to [this](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/prelude.sw), but there's no mention to `B512`.

Anyway, I believe `Rust` and `Typescript` SDK differ in some aspects.

Perhaps @luizstacio or @digorithm can shine a light on this matter.

**Comment by digorithm** [comment]
> Are these stdlib types documented somewhere?

@arboleya some are documented [here](https://fuellabs.github.io/sway/v0.30.1/basics/blockchain_types.html).

In terms of actual implementation, it differs between the Rust and TS SDKs, in some aspects. For instance, `Option` and `Result` types _are not_ generated in the Rust SDK because Rust natively has `Option` and `Result`, so the SDK basically "maps" the `Option`/`Result` from Sway to `Option`/`Result` from Rust. The TS SDK does something similar, but with different mappings/strategies (e.g. there's no `Result<T>` in Typescript).

Regarding this:

> Should I consider this type for the new https://github.com/FuelLabs/fuels-ts/pull/570?

If this is where all the other Sway/std-lib types are handled, yes, `B512` should be part of it!

**Comment by arboleya** [comment]
> @arboleya some are documented [here](https://fuellabs.github.io/sway/v0.30.1/basics/blockchain_types.html).

But there's no mention of `B512`  either. 🤔 

I was trying to understand where I could get a list of `all std types` for easy referencing.

> If this is where all the other Sway/std-lib types are handled, yes, `B512` should be part of it!

Thank you, I'll move the topic to a dedicated issue on the `fuels-ts`.
