### ISSUE TITLE
Error when using `ParamType::try_from_type_application` for `Vec<T>`

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuels-rs#862]
Issue
- Getting the following error ```help: message: called `Option::unwrap()` on a `None` value``` when attempting to call `ParamType::try_from_type_application` on a function input that involves a `Vec<T>`
- I see that `ParamType::try_from_type_application` takes as input a `TypedApplication` and a mapping of all known `TypeDeclaration` type IDs, and the corresponding `TypeDeclaration` for those IDs.
- However when I pass in my `TypedApplication` and mapping of `TypeDeclarations` and their type IDs, I get the error above ☝🏽 
- After a bit of research I think this _might_ be due to [this line](https://github.com/FuelLabs/fuels-rs/blob/master/packages/fuels-types/src/param_types.rs#L139) in `param_types.rs`, which passes an empty `parent_generic_params` to `Self::resolve`, which leads the corresponding `.unwrap()` on the `find()` in `resolve` to panic [here](https://github.com/FuelLabs/fuels-rs/blob/master/packages/fuels-types/src/param_types.rs#L153)?
  - This is my guess at least, opening this issue to get clarity

Additional details
- This is what the `TypeDeclaration` for my generic looks like in my `type_lookup`:

```rust
{23: TypeDeclaration { type_id: 23, type_field: "struct Vec", components: Some([TypeApplication { name: "buf", type_id: 20, type_arguments: Some([TypeApplication { name: "", type_id: 8, type_arguments: None }]) }, TypeApplication { name: "len", type_id: 25, type_arguments: None }]), type_parameters: Some([8]) }
```

- The specific `TypeApplication` that is causing the error is:

```rust 
TypeApplication { name: "v", type_id: 23, type_arguments: Some([TypeApplication { name: "", type_id: 26, type_arguments: None }]) }
```

Expected behavior
- I would expect `try_from_type_application` to not panic
- ~~Labeling as `bug` because I seem to be passing a well-formed `TypeApplication` to `try_from_type_application` - but of course, I might not be informed, so feel free to remove the label if need be.~~

Let me know if you need any more info or if I'm doing something incorrectly here 🤔 

Dependencies
- `fuels-code-gen 0.37`
- `fuels-core 0.37`

**Comment by segfault-magnet** [comment]
The type lookup is missing a lot of the types mentioned in the type application that would normally be generated in the abi.json if you use a Vec in Sway. Types such as: 
* the vector inner type 
* The raw vector type (part of the Vec struct in sway)
* The generic type (would be given as a "generic T" in the abi.json) 
* the raw ptr declaration
* u64 declaration used by `cap` and `len` parts of the `Vec` structure.

When I added all that was missing, the param type resolved correctly. 

However, I will open up a new task to make the error more understandable so that, if this happens again, we don't have to dig.
