### ISSUE TITLE
make the `Account` trait object safe

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/fuels-rs#925]
Due to the `Account` trait not being object safe ([read up on object-safety](https://doc.rust-lang.org/reference/items/traits.html#object-safety)) it started appearing in a couple of places throughout the code. Most notably when constructing contract instances you'd now have to specify the account, e.g. `MyContract<UnlockedWallet>`. 

Ideally, we could have hidden this if the `Account` trait was object-safe. `MyContract` would contain `Box<dyn Account>`. 

We can retain the generic parameter in other places for improved UX, for example:

Even though `MyContract` would now hold the account as a `Box<dyn Account>` you can still use generics in its constructor:
```rust
            pub fn new(contract_id: Bech32ContractId, account: impl Account) -> Self {
                let log_decoder = LogDecoder {
                    type_lookup: logs::log_type_lookup(&[], contract_id.clone().into()),
                };
                Self {
                    contract_id,
                    account: Box::new(account),
                    log_decoder,
                }
```
(The example is a bit simplified, you'd also need to decide the lifetimes of the generic. Probably is fine with being `T: Account + 'static`. Also `Send` would probably also be a requirement.)

This way the users can do `MyContract::new(..,wallet)` and `MyContract::new(.., predicate)` without having to do the `Box::new` wrapping themselves. 

The performance impact of the change will probably be negligible compared to the cost of the network call which is bound to happen in most (if not all) execution paths making use of the contracts `account`.

@MujkicA noted during the sync that the need to treat witness indexes differently between wallets and predicates is why the trait is not object-safe.

If this turns out to be the case, we might benefit from implementing what was previously discussed with regard to not having the user calculate the witness index themselves but improving the SDK to do that automatically before sending the tx.

Whether or not this benefits the issue at hand is left to the assignee to determine.

**Comment by MujkicA** [comment]
@segfault-magnet and I thoroughly investigated different approaches such as transforming the `Account` trait into an enum, making changes to the `TransactionBuilder` so that `Account` methods don't contain generic params. As part of this, we also considered removing the `CreateTransactionBuilder` entirely under the argument that custom Create transactions are a very niche use case. 
Ultimately, all approaches resulted in significant negative impact to either code quality, maintenance costs or UX.
We agreed that it would be best to postpone this until its importance justifies the associated costs.
