### ISSUE TITLE
Support `.trim()` for `SizedAsciiString`

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuels-rs#953]
- Here is the issue I created on the indexer project to track this https://github.com/FuelLabs/fuel-indexer/issues/853
  - This issue has all the context, happy to provide more if needed

**Comment by iqdecay** [comment]
So we can't actually get this API `my_string.trim()` to work since it implies a type mutation (you would go from `SizedAsciiString<12>` to `SizedAsciiString<5>` for instance. I'm actually not sure how you would implement the whitespacing with the `SizedAsciiString` for the same reason.

**Comment by iqdecay** [comment]
Ok I see what you mean. I think we have two things to do here:
- Find a way to consistently pad a "short" string to for instance a `SizedAsciiString<100>`. We can definitely build an helper function that would take a `&str` and return a padded `SizedAsciiString<100>`
- We can also probably build a function that takes a padded `SizedAsciiString<100>` and returns a trimmed `&str`.

But I'm pretty sure it's not possible build a function that does `SizedAsciiString<100> -> SizedAsciiString<{whatever the trimmed length is}>` because you would need to dynamically know the trimmed size.

**Comment by iqdecay** [comment]
Do you think the conversion to/from `&str` is good, or would to/from `String` be better?
